hashing trick filter
Waikato/moa pull request #230
Opened 2021-03-16 15:56 UTC by marouabahri

Adding the hashing trick filter.

2021-03-17 00:58 UTC, garawalid requested changes
@marouabahri 
I left you some comments, otherwise, It looks good to me.  
Also, It would be nicer if we have some unit tests for this class.

2021-03-17 00:58 UTC, garawalid commented on moa/src/main/java/moa/streams/filters/HashingTrickFilter.java
> +import com.google.common.hash.Hashing;
You forget to include the guava dependency.
At `moa/moa/pom.xml` add the following dependency:
```xml
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>29.0-jre</version>
    </dependency>
```

2021-03-17 00:58 UTC, garawalid commented on moa/src/main/java/moa/streams/filters/HashingTrickFilter.java
> +                                com.google.common.hash.HashFunction hashFunction) {
I'd write: 
```java
import com.google.common.hash.HashFunction;
/*
.
.
*/

 public  double[] hashVector(Instance instance, int n, HashFunction hashFunction) {
```

2021-03-22 21:05 UTC, garawalid approved these changes
LGTM

2021-03-23 11:08 UTC, marouabahri commented on moa/src/main/java/moa/streams/filters/HashingTrickFilter.java
> +                                com.google.common.hash.HashFunction hashFunction) {
Done, many thanks Walid :)

2021-04-23 09:03 UTC, merged